name: neurvps
channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=24.2
  - numpy=1.24.3
  - matplotlib=3.7.2
  - scikit-image=0.20.0
  - opencv=4.10.0
  - imageio=2.33.1
  - tqdm=4.67.1
  - docopt=0.6.2
  - pyyaml=6.0.2
  - tensorboardx=2.6.2.2
  - cudatoolkit-dev=12.4.131  # Optional for CUDA development tools
  - pip:
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - sympy==1.13.3